{% set name = "python-installer" %}
{% set pypi_name = "installer" %}
{% set version = "0.7.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ pypi_name[0] }}/{{ pypi_name }}/{{ pypi_name }}-{{ version }}.tar.gz
  sha256: a26d3e3116289bb08216e0d0f7d925fcef0b0194eedfa0c944bcaaa106c4b631

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - flit-core >=3.2.0,<4
  run:
    - python >=3.7

test:
  imports:
    - installer

about:
  home: https://github.com/pradyunsg/installer
  summary: A library for installing Python wheels.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
